apiVersion : apps/v1
kind: Deployment
metadata:
  name: antniocarlodfiapcloudgamespaymentsapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antniocarlodfiapcloudgamespaymentsapi
  template:
    metadata:
      labels:
        app: antniocarlodfiapcloudgamespaymentsapi 
    spec:
      containers:
        - name: antniocarlodfiapcloudgamespaymentsapi 
          image: fgcacr13245.azurecr.io/antniocarlodfiapcloudgamespaymentsapi
          ports:
          - containerPort: 8080