apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secrets
type: Opaque
stringData:
  ConnectionStrings__MySQL: $(MYSQL_CONNECTION)

  Authentication__Key: $(AUTH_KEY)

  ElasticSearch__ApiKey: $(ELASTIC_API_KEY)

  AzureServiceBus__ConnectionString: $(SERVICEBUS_CONNECTION)